### ISSUE TITLE
Enhancement: replace core implementation with typer/click

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/mdpre#2]
- (-) first non std lib dependency
- (+) readability and reusability

**Comment by MartinPacker** [comment]
I don’t understand this. Please elaborate.

**Comment by 42sol-eu** [comment]
the mdpre library is stdlib only at the moment and if Pyto would force us to copy the files to its local storage that might be a worthwhile feature.

Onnthe other hand is mdpre packed with arguments that would benefit from automatic documentation and other nice stuff like prompting the user for a mandatory value.

I could creste a mock up to show what I am referring to.

**Comment by 42sol-eu** [comment]
I started a raw frame as a wrapper of both tools.
See https://github.com/42sol-eu/cute_gearbox.git.

I would like to start on integrating typer into mdpre first.

Using mdpre or md2pptx from other scripts would make it necessay to make the projects importable (__init__.py and py-extension on mdpre.

**Comment by MartinPacker** [comment]
OK. Go with mdpre first - as I want to do line continuation in md2pptx when I get a moment.

And tell me how to test this. (I will before I close the Issue.) This should make it into 0.4.6.

**Comment by MartinPacker** [comment]
Not going to do this.
