### ISSUE TITLE
White space removal in included files breaks formatting of blockquotes

### ISSUE THREAD

**Issue by NRCgg** [MartinPacker/mdpre#25]
When I included a file that had blockquotes which (on GitHub at least) needs 2 spaces at the end of the line to indicate that it's the end of the line, those spaces got stripped out and the blockquote was then incorrectly formatted in the resulting output from mdpre.

**Comment by MartinPacker** [comment]
Can you show me a simple example, please?

**Comment by NRCgg** [comment]
Here are some files that you can use to reproduce the issue I am seeing.   I included two "mdp" files and a "demo.sh" file to show how I ran mdpre.
[blockquote.mdp.txt](https://github.com/MartinPacker/mdpre/files/14528093/blockquote.mdp.txt)
[demo.sh.txt](https://github.com/MartinPacker/mdpre/files/14528094/demo.sh.txt)
[top.mdp.txt](https://github.com/MartinPacker/mdpre/files/14528095/top.mdp.txt)

**Comment by MartinPacker** [comment]
Thank you. And which platform are you running this on? In case it's a Windows vs Mac vs z/OS etc thing.

**Comment by NRCgg** [comment]
RHEL 8.

**Comment by MartinPacker** [comment]
Fixed in [v0.6.8](https://github.com/MartinPacker/mdpre/releases/tag/v0.6.8). Please test and confirm before closing this isssue. Thanks!

**Comment by NRCgg** [comment]
Successfully tested.  It works perfectly!  TYSM for the quick fix!

Closing issue.

**Comment by MartinPacker** [comment]
You're very welcome. And thanks for pointing out the implications of the bug and providing a simple test case.
