### ISSUE TITLE
Access global toFile without passing

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/mdpre#3]
the global variable `toFile` is accessed in line 25, 54 ... without passing it to the function. it is neither declared as `global` nor checked if it is opened.

Solutions?

- create a mdpre class that has a member `toFile` and opens the file at creation. then  moving all corresponding functions into the interface of the class so the file is always available.
- pass `toFile` as a parameter on every function call that needs it.
- mark `toFile` as global innige functions that access it and check it on type FileObject (this might be even done in `writeMarkdown()`) 
- move the `toFile` inside `writeMarkdown()` and check it there

**Comment by MartinPacker** [comment]
Do you want to do this one? If so please create a branch to work on.

**Comment by 42sol-eu** [comment]
sure thing. 

my idea would be to move toFile inside a class that also has the `writeMarkdown()` function. 

that should not be invasive to the code.

**Comment by MartinPacker** [comment]
Sounds good to me.

**Comment by 42sol-eu** [comment]
OK. I am having a chicken and egg problem with this.

There are three basic ways to do it:

- create a writer class and move all functions that call writeMarkdown or use toFile into that class 

> This heavily moves stuff so it is hard to merge later!

- create a lazy check inside the writeMarkdown function and do the create_writer from a global variable.

> Much less intrusive but a bit ugly in the writeMarkdown function.

- only mark the toFile as a global variable in the corresponding functions and maybe check it for None before using it in writeMarkdown

> A good measure to remove the lingering crash whilst keeping the code.

**What would you prefer?**

**Comment by MartinPacker** [comment]
The class way is best.

**Comment by 42sol-eu** [comment]
OK. I will do my best not to break anything here.
I love the class way the best too.

**Comment by MartinPacker** [comment]
This is lost in the mists of time. Closing. Reopen if still relevant.
