### ISSUE TITLE
Bug: Temp files are not removed due to intention error

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/mdpre#7]
https://github.com/MartinPacker/mdpre/blob/68afa49a4121986320311b4fc3e5a7d65b416141/mdpre#L753

the line does not belong in the verbose block

**Comment by MartinPacker** [comment]
You're right. Indentation error indeed. Please fix - as you're in the code.

**Comment by 42sol-eu** [comment]
done

**Comment by MartinPacker** [comment]
Did this get included as part of the PR you made a few days ago?

**Comment by MartinPacker** [comment]
This got fixed at some point and the fix is in shipping code. Closing.
